/*
 For license information please see main.js.LICENSE.txt */
(function(x){var r=window.AmazonUIPageJS||window.P,L=r._namespace||r.attributeErrors,m=L?L("PRIVCONAssets@centralized-prompting",""):r;m.guardFatal?m.guardFatal(x)(m,window):m.execute(function(){x(m,window)})})(function(x,r,L){function m(e,r,m){r in e?Object.defineProperty(e,r,{value:m,enumerable:!0,configurable:!0,writable:!0}):e[r]=m;return e}var p="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===
Symbol&&e!==Symbol.prototype?"symbol":typeof e};x.when("3p-promise").register("@amzn/consent-orchestration-client-sdk",function(e){var m;(function(){function x(a){var b;(b=function(a){if(Array.isArray(a))return O(a)}(a))||(b="undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"]?Array.from(a):void 0);if(!(a=b||function(a,b){if(a){if("string"==typeof a)return O(a,b);var d={}.toString.call(a).slice(8,-1);return"Object"===d&&a.constructor&&(d=a.constructor.name),"Map"===d||"Set"===
d?Array.from(a):"Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d)?O(a,b):void 0}}(a)))throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");return a}function O(a,b){(null==b||b>a.length)&&(b=a.length);for(var d=0,l=Array(b);d<b;d++)l[d]=a[d];return l}function h(){for(var a=arguments.length,b=Array(a),d=0;d<a;d++)b[d]=arguments[d];return b.filter(function(a){return a}).join(".")}
function z(){for(var a=[],b=arguments.length,d=Array(b),l=0;l<b;l++)d[l]=arguments[l];d.forEach(function(b){Array.isArray(b)?a.push.apply(a,x(b)):a.push(b)});b=a.filter(function(a){return"string"==typeof a&&""!==a.trim()}).map(function(a){return a.replace(/,/g,"-")});return h.apply(void 0,x(b))}function t(a,b){(null==b||b>a.length)&&(b=a.length);for(var d=0,l=Array(b);d<b;d++)l[d]=a[d];return l}function S(a){return a>Date.now()-P.promptTimeWindow*Y}function L(a){var b=Date.now();return a>=P.promptsUntilCooldown?
b+P.readCooldownDuration*Y:void 0}function E(a){return E="function"==typeof Symbol&&"symbol"==p(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":p(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":p(a)},E(a)}function T(a,b){var d=Object.keys(a);if(Object.getOwnPropertySymbols){var l=Object.getOwnPropertySymbols(a);b&&(l=l.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));
d.push.apply(d,l)}return d}function U(a){for(var b=1;b<arguments.length;b++){var d=null!=arguments[b]?arguments[b]:{};b%2?T(Object(d),!0).forEach(function(b){var l,f=d[b];a:if("object"==E(b)&&b){var c=b[Symbol.toPrimitive];if(void 0!==c){b=c.call(b,"string");if("object"!=E(b))break a;throw new TypeError("@@toPrimitive must return a primitive value.");}b=String(b)}(l="symbol"==E(b)?b:b+"")in a?Object.defineProperty(a,l,{value:f,enumerable:!0,configurable:!0,writable:!0}):a[l]=f}):Object.getOwnPropertyDescriptors?
Object.defineProperties(a,Object.getOwnPropertyDescriptors(d)):T(Object(d)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(d,b))})}return a}function y(a,b){var d,c=J(a,b),I=(d=c.prompts,[Date.now()].concat(function(a){if(Array.isArray(a))return t(a)}(d)||function(a){if("undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"])return Array.from(a)}(d)||function(a,b){if(a){if("string"==typeof a)return t(a,b);var d={}.toString.call(a).slice(8,-1);return"Object"===
d&&a.constructor&&(d=a.constructor.name),"Map"===d||"Set"===d?Array.from(a):"Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d)?t(a,b):void 0}}(d)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}()).filter(S).sort(function(a,b){return b-a}).slice(0,P.promptsUntilCooldown));F(a,{principal:c.principal,prompts:I,defer:L(I.length)},b)}function J(a,b){var d,c,I,f,e=a.id(),
Z={principal:e,prompts:[]};try{var k=a.get(ca);if(!k)return Z;var M=JSON.parse(r.atob(k));return b.emitCount(h(b.appName,g.SERVICE,g.STORE,g.READ)),M.principal===e||(d=e,c=null!==(f=c=M.principal)&&void 0!==f?f:"",(d=null!==(I=d)&&void 0!==I?I:"").length!=c.length&&d.startsWith(c))?U(U({},M),{},{principal:e}):Z}catch(ia){return b.emitCount(h(b.appName,g.SERVICE,g.STORE,g.READ,g.ERROR)),Z}}function F(a,b,d){try{var c=r.btoa(JSON.stringify(b));a.set(ca,c);d.emitCount(h(d.appName,g.SERVICE,g.STORE,g.WRITE))}catch(I){d.emitCount(h(d.appName,
g.SERVICE,g.STORE,g.WRITE,g.ERROR))}}function A(a){return A="function"==typeof Symbol&&"symbol"==p(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":p(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":p(a)},A(a)}function v(a){var b="function"==typeof Map?new Map:void 0;return v=function(a){function d(){return function(a,b,d){if(Q())return Reflect.construct.apply(null,arguments);var c=[null];
c.push.apply(c,b);c=new (a.bind.apply(a,c));return d&&B(c,d.prototype),c}(a,arguments,C(this).constructor)}if(null===a||!function(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(f){return"function"==typeof a}}(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,d)}return d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}}),
B(d,a)},v(a)}function Q(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(Q=function(){return!!a})()}function B(a,b){return B=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=b,a},B(a,b)}function C(a){return C=Object.setPrototypeOf?Object.getPrototypeOf.bind():function(a){return a.__proto__||Object.getPrototypeOf(a)},C(a)}function K(a){return K="function"==typeof Symbol&&"symbol"==p(Symbol.iterator)?function(a){return"undefined"===
typeof a?"undefined":p(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":p(a)},K(a)}function c(){function a(a,b,d){return Object.defineProperty(a,b,{value:d,enumerable:!0,configurable:!0,writable:!0}),a[b]}function b(a,b,d,c){b=Object.create((b&&b.prototype instanceof l?b:l).prototype);c=new m(c||[]);return x(b,"_invoke",{value:da(a,d,c)}),b}function d(a,b,d){try{return{type:"normal",arg:a.call(b,d)}}catch(ea){return{type:"throw",
arg:ea}}}function l(){}function g(){}function f(){}function k(b){["next","throw","return"].forEach(function(d){a(b,d,function(a){return this._invoke(d,a)})})}function n(a,b){function u(c,q,V,f){c=d(a[c],a,q);if("throw"!==c.type){var G=c.arg;return(c=G.value)&&"object"==K(c)&&t.call(c,"__await")?b.resolve(c.__await).then(function(a){u("next",a,V,f)},function(a){u("throw",a,V,f)}):b.resolve(c).then(function(a){G.value=a;V(G)},function(a){return u("throw",a,V,f)})}f(c.arg)}var c;x(this,"_invoke",{value:function(a,
d){function q(){return new b(function(b,c){u(a,d,b,c)})}return c=c?c.then(q,q):q()}})}function da(a,b,c){var u=C;return function(q,f){if(u===F)throw Error("Generator is already running");if(u===A){if("throw"===q)throw f;return{value:w,done:!0}}c.method=q;for(c.arg=f;;){if(q=c.delegate)if(q=M(q,c)){if(q===H)continue;return q}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(u===C)throw u=A,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);u=F;
q=d(a,b,c);if("normal"===q.type){if(u=c.done?A:J,q.arg===H)continue;return{value:q.arg,done:c.done}}"throw"===q.type&&(u=A,c.method="throw",c.arg=q.arg)}}}function M(a,b){var c=b.method,u=a.iterator[c];if(u===w)return b.delegate=null,"throw"===c&&a.iterator.return&&(b.method="return",b.arg=w,M(a,b),"throw"===b.method)||"return"!==c&&(b.method="throw",b.arg=new TypeError("The iterator does not provide a '"+c+"' method")),H;c=d(u,a.iterator,b.arg);return"throw"===c.type?(b.method="throw",b.arg=c.arg,
b.delegate=null,H):(c=c.arg)?c.done?(b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=w),b.delegate=null,H):c:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,H)}function W(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function h(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function m(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(W,
this);this.reset(!0)}function r(a){if(a||""===a){var b=a[y];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function G(){for(;++c<a.length;)if(t.call(a,c))return G.value=a[c],G.done=!1,G;return G.value=w,G.done=!0,G};return b.next=b}}throw new TypeError(K(a)+" is not iterable");}c=function(){return D};var w,D={},z=Object.prototype,t=z.hasOwnProperty,x=Object.defineProperty||function(a,b,c){a[b]=c.value},p="function"==typeof Symbol?Symbol:{},y=p.iterator||
"@@iterator",E=p.asyncIterator||"@@asyncIterator",B=p.toStringTag||"@@toStringTag";try{a({},"")}catch(u){a=function(a,b,c){return a[b]=c}}D.wrap=b;var C="suspendedStart",J="suspendedYield",F="executing",A="completed",H={};p={};a(p,y,function(){return this});var v=Object.getPrototypeOf;(v=v&&v(v(r([]))))&&v!==z&&t.call(v,y)&&(p=v);var N=f.prototype=l.prototype=Object.create(p);return g.prototype=f,x(N,"constructor",{value:f,configurable:!0}),x(f,"constructor",{value:g,configurable:!0}),g.displayName=
a(f,B,"GeneratorFunction"),D.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===g||"GeneratorFunction"===(a.displayName||a.name))},D.mark=function(b){return Object.setPrototypeOf?Object.setPrototypeOf(b,f):(b.__proto__=f,a(b,B,"GeneratorFunction")),b.prototype=Object.create(N),b},D.awrap=function(a){return{__await:a}},k(n.prototype),a(n.prototype,E,function(){return this}),D.AsyncIterator=n,D.async=function(a,c,d,f,l){void 0===l&&(l=e);var q=new n(b(a,c,d,f),l);
return D.isGeneratorFunction(c)?q:q.next().then(function(a){return a.done?a.value:q.next()})},k(N),a(N,B,"Generator"),a(N,y,function(){return this}),a(N,"toString",function(){return"[object Generator]"}),D.keys=function(a){var b=Object(a),c=[],d;for(d in b)c.push(d);return c.reverse(),function R(){for(;c.length;){var a=c.pop();if(a in b)return R.value=a,R.done=!1,R}return R.done=!0,R}},D.values=r,m.prototype={constructor:m,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=w,this.done=
!1,this.delegate=null,this.method="next",this.arg=w,this.tryEntries.forEach(h),!a)for(var b in this)"t"===b.charAt(0)&&t.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=w)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return l.type="throw",l.arg=a,c.next=b,d&&(c.method="next",c.arg=w),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var f=this.tryEntries[d],l=
f.completion;if("root"===f.tryLoc)return b("end");if(f.tryLoc<=this.prev){var e=t.call(f,"catchLoc"),g=t.call(f,"finallyLoc");if(e&&g){if(this.prev<f.catchLoc)return b(f.catchLoc,!0);if(this.prev<f.finallyLoc)return b(f.finallyLoc)}else if(e){if(this.prev<f.catchLoc)return b(f.catchLoc,!0)}else{if(!g)throw Error("try statement without catch or finally");if(this.prev<f.finallyLoc)return b(f.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=
this.prev&&t.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var f=d;break}}f&&("break"===a||"continue"===a)&&f.tryLoc<=b&&b<=f.finallyLoc&&(f=null);c=f?f.completion:{};return c.type=a,c.arg=b,f?(this.method="next",this.next=f.finallyLoc,H):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),H},finish:function(a){for(var b=
this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),h(c),H}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;h(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){return this.delegate={iterator:r(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=w),H}},D}function k(a,b,c,l,g,f,k){try{var d=
a[f](k),n=d.value}catch(M){return void c(M)}d.done?b(n):e.resolve(n).then(l,g)}function n(){var a;return a=c().mark(function I(a,l){var d,g,k=arguments;return c().wrap(function(c){for(;;)switch(c.prev=c.next){case 0:d=2<k.length&&void 0!==k[2]?k[2]:3,g=0;case 2:return c.prev=2,c.next=5,a(l);case 5:return c.abrupt("return",c.sent);case 8:if(c.prev=8,c.t0=c.catch(2),!(++g>=d)){c.next=13;break}throw c.t0;case 13:return c.next=15,new e(function(a){return setTimeout(a,100)});case 15:if(g<d){c.next=2;break}case 16:case "end":return c.stop()}},
I,null,[[2,8]])}),n=function(){var c=this,l=arguments;return new e(function(d,f){function g(a){k(n,d,f,g,e,"next",a)}function e(a){k(n,d,f,g,e,"throw",a)}var n=a.apply(c,l);g(void 0)})},n.apply(this,arguments)}function W(a,b,c,l){var d=b.appName;return function(a,b){return n.apply(this,arguments)}(a,l,4<arguments.length&&void 0!==arguments[4]?arguments[4]:3).then(function(a){return b.emitCount(h(d,g.SERVICE,z(null==l?void 0:l.metricDimensions),c)),a}).catch(function(a){throw b.emitCount(h(d,g.SERVICE,
c,g.ERROR)),new aa("failed to ".concat(c.toLowerCase()," consent for ").concat(d),a);})}function X(a,b,c){var d=b||fa,k=c||ha;return{prompt:function(){return function(a,b,c){var d=b.appName;return function(a,b){var c;a=J(a,b);return Date.now()>(null!==(c=a.defer)&&void 0!==c?c:0)}(c,b)?a().then(function(a){return b.emitCount(h(d,g.SERVICE,z(null==a?void 0:a.metricDimensions),g.PROMPT)),y(c,b),a}).catch(function(a){var f,e=a.status||(null===(f=a.http)||void 0===f?void 0:f.status)||0;if(429!==e&&204!==
e)throw b.emitCount(h(d,g.SERVICE,g.PROMPT,g.ERROR)),new aa("failed to prompt for consent for "+d,a);a=J(c,b);F(c,{principal:a.principal,prompts:a.prompts,defer:Date.now()+P.writeCooldownDuration*Y},b);!0}):function(a){return new e(function(b){a.emitCount(h(a.appName,g.SERVICE,g.PROMPT,g.SKIP));b(null)})}(b)}(a.prompt,d,k)},accept:function(b){return W(a.accept,d,g.ACCEPT,b)},decline:function(b){return W(a.decline,d,g.DECLINE,b)},customize:function(b){return function(a,b,c){var d=b.appName;return a(c).then(function(a){return b.emitCount(h(d,
g.SERVICE,z(null==c?void 0:c.metricDimensions),g.CUSTOMIZE)),a}).catch(function(a){throw b.emitCount(h(d,g.SERVICE,g.CUSTOMIZE,g.ERROR)),new aa("failed to customize consent for "+d,a);})}(a.customize,d,b)}}}var w={d:function(a,b){for(var c in b)w.o(b,c)&&!w.o(a,c)&&Object.defineProperty(a,c,{enumerable:!0,get:b[c]})},o:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},r:function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});
Object.defineProperty(a,"__esModule",{value:!0})}},ba={};w.r(ba);w.d(ba,{initialize:function(){return X}});var g=function(a){return a.SERVICE="cos",a.PROMPT="prompt",a.ACCEPT="accept",a.DECLINE="decline",a.CUSTOMIZE="customize",a.STORE="store",a.READ="read",a.WRITE="write",a.ERROR="error",a.SKIP="skip",a}({}),fa={appName:"unknown",emitCount:function(a,b){},emitTiming:function(a,b){}},P=JSON.parse('{"J":{"promptsUntilCooldown":5,"promptTimeWindow":10,"readCooldownDuration":15,"writeCooldownDuration":1440}}').J,
Y=6E4,ca="sp-cc-pcl",ha={id:function(){return"unknown"},set:function(a,b){},get:function(a){return""}},aa=function(a){function b(a,c){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var d=b;var g=[a];d=C(d);d=Q()?Reflect.construct(d,g||[],C(this).constructor):d.apply(this,g);if(!d||"object"!=A(d)&&"function"!=typeof d){if(void 0!==d)throw new TypeError("Derived constructors may only return object or undefined");if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
d=this}return d.message=a,d.cause=c,d.cause=c,d.name="ConsentOrchestrationError",Object.setPrototypeOf(d,b.prototype),d}return function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&B(a,b)}(b,a),c=b,Object.defineProperty(c,"prototype",{writable:!1}),c;var c}(v(Error));m=ba})();return m});
"use strict";x.when("A","3p-promise","a-util","@amzn/consent-orchestration-client-sdk","ready").execute("centralized-prompting",function(e,p,L,O){var h,z,t=function(){},S={0:(h={name:"cc.banner"},m(h,"NO_VALUE","bannerPopUp"),m(h,"REJECT_ALL",".rejectall.linkbutton"),h),4:{name:"ads.banner"},5:{name:"datashare.banner"},42:{name:"quebec.banner"}},X=(z={},m(z,"NO_VALUE",".popup"),m(z,"ACCEPT_ALL",".acceptAll"),m(z,"REJECT_ALL",".rejectall"),m(z,"ACCEPT_PARTIAL",".customize"),z),E=function(c){return new p(function(k,
n){e.post("/privacyprefs/retail/v3/banner",{params:{consent:c.payload.url,consentTypes:c.consentTypes},paramsFormat:"json",accepts:"application/json",contentType:"application/json",timeout:5E3,headers:{"anti-csrftoken-a2z":c.csrfToken},success:function(c){k(c)},error:function(c){n(c)}})})},T=["x-acb","x-main","x-tacb"],U=function(){return r.fwcimData&&fwcimData.customerId||Object.keys(L.cookies.getAll()||{}).some(function(c){return T.some(function(e){return c.startsWith(e)})})?"1":"0"},y=e.capabilities.localStorage?
localStorage:{getItem:function(c){return null},setItem:t,removeItem:t};h=r.ue&&"function"===typeof ue.count?function(c){return ue.count(c,1)}:t;var J=r.uet&&r.uex?{start:function(){return uet("bb","centralizedConsentBanner",{wb:1})},stop:function(){return uex("ld","centralizedConsentBanner",{wb:1})}}:{start:t,stop:t};J.start();var F=O.initialize({prompt:function(){return new p(function(c,k){e.get("/privacyprefs/retail/v3/banner",{success:function(n){n||k(Error("No Data"));var h=document.createElement("div");
h.id="sp-cc-wrapper";h.innerHTML=n;n=h.querySelector('input[type\x3d"hidden"][name\x3d"disclosureDecision"]');h={banner:h,metricDimensions:[n?n.value:"unknown"]};y.getItem("sp-cc-pending")&&(n=h.banner.querySelector("#sp-cc-error"))&&(n.className=(" "+n.className+" ").replace(" aok-hidden "," "));y.removeItem("sp-cc-pending");Q(h.banner);K(e.$("#cos-banner"),"NO_VALUE");c(h)},error:function(c){k(c)}})})},accept:function(c){return E(c)},decline:function(c){return E(c)},customize:function(c){return new p(function(e){e(c)})}},
{appName:"sp",emitCount:h,emitTiming:t},{id:function(){return L.cookies.get("session-id")+"|"+U()},get:function(c){return y.getItem(c)},set:function(c,e){return y.setItem(c,e)}}),A=void 0,v=function(){var c=e.$("#cos-banner").outerHeight();"number"!==typeof c||0>=c?document.querySelector("html").style.removeProperty("scroll-padding-bottom"):(c+="px",e.capabilities.mobile?document.querySelector("#a-page").style.marginBottom=c:document.body.style.paddingBottom=c,document.querySelector("html").style.setProperty("scroll-padding-bottom",
c))},Q=function(c){var k=e.$("#a-page \x3e *:not(script)").first();k.length?k.before(c):document.body.appendChild(c);x.when("a-expander").execute(function(c){c.initializeExpanders()})};F.prompt().then(function(){J.stop();A=e.on("orientationchange resize",v);v()}).catch(function(c){J.stop();throw c;});var B=function(){e.$("#sp-cc-wrapper").remove();y.setItem("sp-cc-pending","1");A&&e.off(A);v()},C=function(c,e){e.$event.preventDefault();var k=c.find('[name\x3d"anti-csrftoken-a2z"]'),h=c.find('[name\x3d"disclosureDecision"]');
c=c.find('[name\x3d"consentTypes"]').val();return{payload:e.data,csrfToken:k.val(),metricDimensions:[h.val()],consentTypes:c}};e.declarative("banner-accept-all","click",function(c){var k=e.$("#cos-banner");c=C(k,c);B();F.accept(c).then(function(){y.removeItem("sp-cc-pending");K(k,"ACCEPT_ALL")})});e.declarative("banner-reject-all","click",function(c){var k=e.$("#cos-banner");c=C(k,c);B();F.decline(c).then(function(){y.removeItem("sp-cc-pending");K(k,"REJECT_ALL")})});e.declarative("banner-customize",
"click",function(){var c=e.$("#cos-banner"),k=c.find('[name\x3d"disclosureDecision"]');F.customize({metricDimensions:[k.val()]}).then(function(){K(c,"ACCEPT_PARTIAL")})});var K=function(c,k){var h=c.find('[name\x3d"consentTypes"]').val();h&&""!==h.trim()&&0!==h.length&&(h=h.split(","),e.each(h,function(h){if(S.hasOwnProperty(h)&&r.csa&&"function"===typeof r.csa){var n=csa("Events",{producerId:"cdo-privacy"}),m=S[h],p="NO_VALUE"===k,g=m.hasOwnProperty(k)?m[k]:X[k];m=e.contains(g,".")?m.name+g:g;n("log",
{schemaId:"cdo_privacy.anonymia.consent_business_metrics.6",producerId:"cdo-privacy",aaaClientName:"ShoppingPortal",consentType:h,consentValue:m,consentInferredValue:k,consentAdditionalAttribute:"null",clientType:c.find('[name\x3d"clientType"]').val(),privacyCustomerId:c.find('[name\x3d"privacyCustomerId"]').val(),sessionId:c.find('[name\x3d"sessionId"]').val(),userType:c.find('[name\x3d"userType"]').val(),businessDomain:"1",userId:c.find('[name\x3d"userId"]').val(),tollhouseMarketplaceId:"null",
uiEventSource:m,uiEventActionType:p?"bannerPopUp":"buttonClick"})}}))}})});